name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

env:
  PROJECT_ID: chatchuispt
  GKE_CLUSTER: cluster-robin-2
  GKE_ZONE: europe-west1-b
  DEPLOYMENT_NAME: chatchuisptweb
  IMAGE_NAME: chatchuisptweb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests

      - name: SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=robjo82_chatchuisptweb
            -Dsonar.organization=robjo82

      # Authenticate with the Google Cloud CLI.
      - id: auth
        if: github.ref == 'refs/heads/main' # Only authenticate for main branch
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        if: github.ref == 'refs/heads/main' # Only authenticate for main branch
        uses: google-github-actions/setup-gcloud@v1.1.1

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - name: Configure Docker
        if: github.ref == 'refs/heads/main' # Only authenticate for main branch
        run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials, so we can deploy to the cluster
      - name: Get GKE Credentials
        if: github.ref == 'refs/heads/main' # Only authenticate for main branch
        uses: google-github-actions/get-gke-credentials@v1.0.2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # Build the Docker image
      - name: Build
        if: github.ref == 'refs/heads/main' # Only build and push for main branch
        run: |-
          docker build \
            --tag "eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish
        if: github.ref == 'refs/heads/main' # Only build and push for main branch
        run: |-
          docker push "eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA"

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        if: github.ref == 'refs/heads/main' # Only build and push for main branch
        run: |-
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide